apiVersion: apps/v1
kind: Deployment
metadata:
  name: nome-da-aplicacao
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nome-da-aplicacao
  template:
    metadata:
      labels:
        app: nome-da-aplicacao
    spec:
      containers:
        - name: nome-da-aplicacao
          image: <account-id>.dkr.ecr.<sua-regiao>.amazonaws.com/nome-do-repositorio:latest
          ports:
            - containerPort: 3000
